### ISSUE TITLE
Running AutoScript examples with Python 3.5.4

### ISSUE THREAD

**Issue by DavidDierickx** [DeMarcoLab/config#2]
Could not connect to localhost with AutoScript on Python 3.5.4.  Ran on David's office computer.

```python
>>> from autoscript_sdb_microscope_client import SdbMicroscopeClient
>>> microscope = SdbMicroscopeClient()
>>> microscope.connect('localhost')
Client connecting to [localhost:7520]...
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\David\Anaconda3\envs\fibsem3_5_4\lib\site-packages\autoscript_sdb_microscope_client\sdb_microscope_client.py", line 127, in connect
    raise ApiException(ApiErrorCode.APPLICATION_CLIENT_ERROR, error_message)
autoscript_core.common.ApiException: Client cannot establish connection with server at [localhost:7520]
```
```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                    <pip>
autopep8                  1.4.4                     <pip>
autoscript-core           5.1.0                     <pip>
autoscript-sdb-microscope-client 4.1.0                     <pip>
autoscript-sdb-microscope-client-tests 4.1.0                     <pip>
autoscript-toolkit        4.1.0                     <pip>
Babel                     2.7.0                     <pip>
bleach                    3.1.0                     <pip>
certifi                   2018.8.24             py35_1001    conda-forge
chardet                   3.0.4                     <pip>
coverage                  4.5.3                     <pip>
coveralls                 1.8.0                     <pip>
cycler                    0.10.0                    <pip>
defusedxml                0.6.0                     <pip>
docopt                    0.6.2                     <pip>
docutils                  0.14                      <pip>
entrypoints               0.3                       <pip>
idna                      2.8                       <pip>
imagecodecs               2019.5.22                 <pip>
imagesize                 1.1.0                     <pip>
importlib-metadata        0.17                      <pip>
ipykernel                 5.1.1                     <pip>
ipywidgets                7.4.2                     <pip>
Jinja2                    2.10.1                    <pip>
jsonschema                3.0.1                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.4                     <pip>
jupyter-console           6.0.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.1.0                     <pip>
MarkupSafe                1.1.1                     <pip>
matplotlib                3.0.3                     <pip>
mistune                   0.8.4                     <pip>
nbconvert                 5.5.0                     <pip>
nbformat                  4.4.0                     <pip>
nose                      1.3.7                     <pip>
notebook                  5.7.8                     <pip>
numpy                     1.16.4                    <pip>
opencv-python             4.1.0.25                  <pip>
packaging                 19.0                      <pip>
pandocfilters             1.4.2                     <pip>
pip                       18.0                  py35_1001    conda-forge
pluggy                    0.12.0                    <pip>
prometheus-client         0.6.0                     <pip>
pycodestyle               2.5.0                     <pip>
Pygments                  2.4.2                     <pip>
pyparsing                 2.4.0                     <pip>
pypylon                   1.4.0                     <pip>
PyQt5                     5.12.2                    <pip>
PyQt5_sip                 4.19.17                   <pip>
pyrsistent                0.15.2                    <pip>
pyserial                  3.4                       <pip>
pytest                    4.6.2                     <pip>
pytest-cov                2.7.1                     <pip>
pytest-faulthandler       1.6.0                     <pip>
pytest-mock               1.10.4                    <pip>
pytest-mpl                0.10                      <pip>
python                    3.5.4                         3    conda-forge
python-dateutil           2.8.0                     <pip>
pytz                      2019.1                    <pip>
pywinpty                  0.5.5                     <pip>
PyYAML                    5.1                       <pip>
pyzmq                     18.0.1                    <pip>
qtconsole                 4.5.1                     <pip>
requests                  2.22.0                    <pip>
scikit-image              0.15.0                    <pip>
scipy                     1.3.0                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                40.4.3                   py35_0    conda-forge
snowballstemmer           1.2.1                     <pip>
Sphinx                    2.1.0                     <pip>
sphinx-rtd-theme          0.4.3                     <pip>
sphinxcontrib-applehelp   1.0.1                     <pip>
sphinxcontrib-devhelp     1.0.1                     <pip>
sphinxcontrib-htmlhelp    1.0.2                     <pip>
sphinxcontrib-jsmath      1.0.1                     <pip>
sphinxcontrib-qthelp      1.0.2                     <pip>
sphinxcontrib-serializinghtml 1.1.3                     <pip>
terminado                 0.8.2                     <pip>
testpath                  0.4.2                     <pip>
thermoscientific-logging  5.1.0                     <pip>
tifffile                  2019.5.30                 <pip>
tornado                   6.0.2                     <pip>
urllib3                   1.25.3                    <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
webencodings              0.5.1                     <pip>
wheel                     0.32.0                py35_1000    conda-forge
widgetsnbextension        3.4.2                     <pip>
wincertstore              0.2                   py35_1002    conda-forge
zipp                      0.5.1                     <pip>
```
[environment_fibsem.txt](https://github.com/DeMarcoLab/config/files/3259695/environment_fibsem.txt)

**Comment by GenevieveBuckley** [comment]
I suspect the problem here is that we have the autoscript python packages, but didn't install autoscript itself onto this computer. So it's possible the python bindings have nothing to bind to.
